name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['14', '16']
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm test
      - if: (matrix.os == 'ubuntu-latest') && (matrix.node_version == '10')
        run: npx relcov < coverage/lcov.info > coverage/relcov.info
      - if: (matrix.os == 'ubuntu-latest') && (matrix.node_version == '10')
        uses: sonarsource/sonarcloud-github-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}